### ISSUE TITLE
Week 6 Goals

### ISSUE THREAD

**Issue by dqu123** [BLQ-Software/black-widow#14]
- [x] Check HW 3 (however much you've done by Friday).
- [x] Switch to event queue. See #13.
- [x] Print to separate csv files (and fix logic to clean up files each time script is run).
- [x] Start graphing data to see if we have any bugs / unexpected results.
- [x] Add dynamic routing.
- [x] Add congestion control.

@alphaz99, @omegaphoenix, @nancyywen does this seem like a reasonable plan?
I'm emphasizing this order because we should really start making graphs to analyze.

**Comment by alphaz99** [comment]
Sounds like a good plan
