### ISSUE TITLE
Parameter Fine Tuning

### ISSUE THREAD

**Issue by dqu123** [BLQ-Software/black-widow#25]
@omegaphoenix, @alphaz99, @nancyywen 
It seems like there are some constants that we are picking somewhat arbitrarily like the timeout time, the time between routing table updates, and the routing table send rate.

It would be interesting to be able to optionally pass these values in our script, and maybe have a fine tuning script that runs our script with various parameters and picks the optimal one (reminds me of Othello lol).
This would fall under the realm of self-induced extra work, but I think would be interesting.

**Comment by omegaphoenix** [comment]
@dqu123 I'm thinking we should put this off until we have all the objectives met unless you think it will help us get the simulation more accurate and thus save work on adjusting the parameters as we try to reach the objectives.  Also, we should fix our bug where our simulation is nondeterministic first.
