### ISSUE TITLE
Debugging, Refactoring, and Documentation

### ISSUE THREAD

**Issue by omegaphoenix** [BLQ-Software/black-widow#28]
@dqu123 , @alphaz99 , @nancyywen  Before we get into the extra credit, let's debug and refactor since our network simulator is taking too long for Case 1 and Case 2.  Also everyone should create a list of the things they have accomplished and add it to this issue so we can show Cody on Sunday.

**Comment by alphaz99** [comment]
Stuff we've accomplished:

Things we've accomplished:
    Algorithms:
        TCP Tahoe (Go-back-N, Slow start, Congestion avoidance)
        TCP Reno (Tahoe + Fast Retransmit, Fast Recovery)
        Static routing
        Dynamic routing
    Structure
        Discrete event-based time simulation
        Modularized output
        Clean OOP design
        

Roadmap:
    Week 8:
        Finish implementing FAST TCP
        Analyze graphs
        Review all code and refactor if necessary
        Plan any additional features
    Week 9:
        Work on additional features
        Analyze graphs
        Work on presentation
