### ISSUE TITLE
[Week 5] Refactor GoBackN

### ISSUE THREAD

**Issue by dqu123** [BLQ-Software/black-widow#8]
Issue to organize our thoughts on moving forward and making the code nicer for week 5.
I just wrote down my thoughts on somethings everyone can do, but feel free to discuss and give feedback on what you think.

#### Personal Thoughts/Ideas (TODO)
- By Tuesday:
  - [x] Finish powerpoint.
  - [x] Meet on Tuesday 7 pm, Annenberg 105.
- By the end of next Friday:
  - [ ] @dqu will add routing table, settings class to take in flags like --verbose in run_simulator.py, and hopefully dynamic routing by the end of next Friday.
  - [ ] @omegaphoenix will fix output (see below), modularize tcp code (perhaps make a congestion or tcp class that has an abstract tcp.update_window method), and modularize flow code to adapt to settings.
  - [ ] @alphaz99 will fix output (see below), make links duplex if not already, check link code to see if it supports router packets, and modularize link code to adapt to settings.
  - [ ] @nancyywen will parse case0.json output (see below) into CSV using regular expressions / sed or whatever you want and then graph this data. You will have to wait Justin and Rahul agree on an output format. There's a lot of ways to do regex but basically you would just strip the tags somehow with a script in any language.

#### Output ideas
- [ ] Tags to identify types of statements (```[STATUS], [LINK ACK], [FLOW], [FLOW ACK]``` ... make a list somewhere and commit that document before you start coding it up)
- [ ] Different printing options to be set by flags. Like -v for extra verbose output, etc. (@dqu will try to write a spec for this since I'll be writing the argparse part).

Currently we're dumping a bunch of print statements. We should make it more standard and easier to
grep and regex out what we want. I was thinking we could do tags like ```[LINK ACK] "Packet1", "10" ```
so you can do ```grep [LINK ACK] | sed ...``` to strip the tag and then convert data printing to CSV. So making your data prints already CSV would be convenient if that is the preferred format.

<br/>
Additional objectives to do if you finish the above: 
- [ ] Add unit/regression tests. (This would be very nice.)
- [ ] Add documentation. (Also very nice.)
- [ ] Think about refining our commit standards. (How can we not break the code? lol)

**Comment by nancyywen** [comment]
@alphaz99 @omegaphoenix Hey guys,  let me know if you guys have output before Mon/Tues. If so, I can probably have some graphs ready for our Thursday presentation.

**Comment by alphaz99** [comment]
Regarding the output format, I think it might be better to have a programmatic way to store the data. Each device and link/flow can store the relevant state and the network can access it after each call to send. It seems better to store our information directly with the class instances rather than parsing an output file.
On the other hand, if the graph module will be taking as input an output file, it would make more sense to consolidate the output generation in one class. This would work the same way as now, but with each class storing its relevant information and the network class processing and outputting the data. I would stay away from serializing the data into a pickle dump for raw readability so outputting as a csv format makes the most sense.

**Comment by alphaz99** [comment]
So this is the class structure I am thinking of:
Network
    Devices
    Links / Flows
    Data - update after each call to send.
Data
    all necessary attributes to store data
Devices
    Store state
Links / Flows
    Store state

**Comment by alphaz99** [comment]
See https://github.com/BLQ-Software/black-widow/pull/9 to comment on code and suggestions for refactoring.

**Comment by dqu123** [comment]
What about having a printer class that has a ```printer.print(message, type)``` method and can be configured based on our settings? I think writing to files is useful because it provides a standard format to interface to other programs like Excel or Mathematica. The printer can also call the grapher if the setting is to have real time updates, but gives the option to print to a file as well. The printer would do stuff based on the type so we can decouple the type and message and avoid the regex and messy tags in strings.

**Comment by alphaz99** [comment]
Looks good to me.
